---
steps:
  # Linux x86
  - label: ":linux: linux-i686"
    plugins:
      # Julia installation outside the sandbox
      - JuliaCI/julia#v1:
          version: '1.10'
      - staticfloat/sandbox#v2:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v6.00/package_linux.i686.tar.gz
          rootfs_treehash: "a0c4756ee7827b3a75d4a62ff543315c1547e3d6"
          uid: 1000
          gid: 1000
      # Julia installation inside the sandbox
      - JuliaCI/julia#v1:
          version: "1.12"
          arch: "i686"
    command: |
      julia --color=yes --code-coverage=@ .ci/run_tests.jl
    agents:
      queue: "julia"
      os: "linux"
      arch: "x86_64"
      cpuset_limited: "true"
  # Linux x86_64
  - label: ":linux: linux-x86_64"
    plugins:
      # Julia installation outside the sandbox
      - JuliaCI/julia#v1:
          version: '1.10'
      - JuliaCI/julia-coverage#v1:
          codecov: true
      - staticfloat/sandbox#v2:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v6.00/package_linux.x86_64.tar.gz
          rootfs_treehash: "4dcde853eb5baaa0a8f087b633eaf955dc94b5dc"
          uid: 1000
          gid: 1000
      # Julia installation inside the sandbox
      - JuliaCI/julia#v1:
          version: "1.12"
    command: |
      julia --color=yes --code-coverage=@ .ci/run_tests.jl
    agents:
      queue: "julia"
      os: "linux"
      arch: "x86_64"
      cpuset_limited: "true"
  # macOS aarch64
  - label: ":macos: macos-aarch64"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia --color=yes --code-coverage=@ .ci/run_tests.jl
    agents:
      queue: "julia"
      os: "macos"
      arch: "aarch64"
  # windows x86_64
  - label: ":windows: windows-x86_64"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia --color=yes --code-coverage=@ .ci/run_tests.jl
    agents:
      queue: "julia"
      os: "windows"
      arch: "x86_64"
